name: depe
description: "A new Flutter project."



environment:
  sdk: ^3.5.2


dependencies:
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.0.0



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

dependency_overrides:
  material_color_utilities: ^0.12.0
  meta: ^1.16.0


flutter:

  
  uses-material-design: true
